# CI workflow for FinalProject


name: CI workflow

on:
  push:
    branches: [ "main" ] # Trigger on pushes to the main branch
  pull_request:
    branches: [ "main" ] # Trigger on pull requests to the main branch

jobs:
  build: # name of the job, we named build because it builds the project
    runs-on: ubuntu-latest
    container: python:3.9-slim 

    steps:
      - name: Checkout # name of first step
        uses: actions/checkout@v3 # action to checkout the repository meaning to download the code

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # install dependencies from requirements.txt
      
      - name: Lint with flake8  # this step runs flake8 to lint the code
        run: | # these commands will be run in the terminal and the output will be shown in the github actions log
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
          
        # flake8 helps keep your code clean, readable, and error-free. 
      
      - name: Run unit tests with nose  # this step runs the unit tests using nosetests and 
      # outputs the results in a readable format in the github actions log
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app


  



